### ISSUE TITLE
Ошибки при сборке проекта

### ISSUE THREAD

**Issue by DmitrijMTP** [coder1x/MetaLamp_second_task#1]
1.При запуске сборки ошибки(`npm run dev`, `npm run build`)
![2022-03-24_22-53](https://user-images.githubusercontent.com/85491485/159999305-2f6a679a-15b4-4ddd-8edb-e37729b3c591.png)

2.Не "говорящее"  именование "buildA" пользователю нужно разбираться, что она делает, в дела по названию должно быть понятно
![2022-03-24_22-57](https://user-images.githubusercontent.com/85491485/159999972-fe4f3b2d-51b4-4b07-9312-3c6e1a20265e.png)

3.Пожалуйста, загрузи в репозиторий файлы по которым сверялся pixelperfect, чтобы не было разногласий при сверке

**Comment by DmitrijMTP** [comment]
![2022-04-14_20-08](https://user-images.githubusercontent.com/85491485/163439050-6a507b2c-876e-41b5-842e-03854b024be5.png)
Добавь абсолютный путь в ./assets

**Comment by DmitrijMTP** [comment]
Забыл переименовать имя файла, из-за этого ошибка при сборке
![2022-04-27_00-55](https://user-images.githubusercontent.com/85491485/165399114-4d911b76-9c48-4561-a923-ec7c14c4391f.png)

**Comment by coder1x** [comment]
issues #1 - Rename registration.js to Registration.js
