### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by Everrest1** [coder1x/MetaLamp_second_task#26]
Проверка `if modifier` всегда будет возвращать true

![image](https://user-images.githubusercontent.com/43137324/178938673-1b6c5ac3-e568-44fc-ba03-d29eed868da8.png)

Не нужно разделать `words` и `strings`, вместо этого лучше использовать один массив с объектами в качестве элементов, иначе может быть расхождение в соответствии значений друг другу и с т.з. понимания кода так будет очевиднее

![image](https://user-images.githubusercontent.com/43137324/178939099-b1245846-1df9-4bdd-b1d3-701e5a0839ed.png)

**Comment by Everrest1** [comment]
Согласно БЭМ модификатор не можен использоваться самостоятельно

![image](https://user-images.githubusercontent.com/43137324/179463924-75929e75-7eaa-4252-b56a-d6aac44aad9d.png)

data можно вынести в параметры

![image](https://user-images.githubusercontent.com/43137324/179468584-121ef4ce-4fce-4154-8471-fde55cf820cb.png)

**Comment by Everrest1** [comment]
Закомменченый старый код

![image](https://user-images.githubusercontent.com/43137324/179472374-9eb26869-8a53-4ba1-bfa7-cac909983e2b.png)

**Comment by Everrest1** [comment]
Отформатируй плиз в формате

```
input(
  attr=""
  ...
)
```

![image](https://user-images.githubusercontent.com/43137324/180039826-cabcaee1-7943-4bc1-b19e-7ca526881144.png)

**Comment by Everrest1** [comment]
Добавь ещё отступ плиз для атрибутов, чтобы явно просматривалась вложенность

![image](https://user-images.githubusercontent.com/43137324/180832963-6512852b-85ed-4468-a4f6-67ec7e0914af.png)

**Comment by Azmodan95** [comment]
https://github.com/coder1x/MetaLamp_second_task/blob/48349d1f3080d4e8f13f6d26e3e694d7813415e1/src/components/header/header.pug#L43-L51
У pug доступны [условия](https://pugjs.org/language/conditionals.html), не нужно явно выделять участок с ними как js код чтобы их использовать.
