### ISSUE TITLE
js

### ISSUE THREAD

**Issue by Everrest1** [coder1x/MetaLamp_second_task#35]
getElement выглядит как лишняя абстракция на мой взгляд

![image](https://user-images.githubusercontent.com/43137324/180836100-6c9b2e30-5565-4869-b992-0101004c24cd.png)

**Comment by Everrest1** [comment]
Там где можно использовать константы, лучше использовать константы)

![image](https://user-images.githubusercontent.com/43137324/180836944-8efd34bf-29f6-4e80-9086-246372c5ecd8.png)

Добавление элементов в дом делаем за пределами цикла [п.7.2](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#7.2)

![image](https://user-images.githubusercontent.com/43137324/180837121-f6f3f3ec-caae-48ff-be43-9d349588e9bf.png)

Дату лучше преобразовывать встроенными методами

![image](https://user-images.githubusercontent.com/43137324/180837555-f5961f7c-de01-4300-804c-13d7e28d3552.png)

Использована часть внутренней структуры другого блока, это нарушает независимость

![image](https://user-images.githubusercontent.com/43137324/180838082-40ce178d-f91a-4797-8aeb-9f2b6caa87c7.png)

**Comment by Everrest1** [comment]
Зачем выполнять поиск по тегу? Есть же класс с префиксом js-

![image](https://user-images.githubusercontent.com/43137324/181029534-c37613d6-b4a2-4832-a3c8-9004735bd33e.png)

**Comment by Azmodan95** [comment]
https://github.com/coder1x/MetaLamp_second_task/blob/48349d1f3080d4e8f13f6d26e3e694d7813415e1/src/components/room-card/Slider.js#L125
Здесь происходит создание объекта даты который нужен только, для того чтобы получить дату в числовом варианте. Для этого есть Date.now() чтобы не создавать объект даты.
